= git-bundle-server(1)
:doctype: manpage
:manmanual: Git Bundle Server Manual
:mansource: Git Bundle Server

== NAME

git-bundle-server - create, manage, and host Git bundle content

== SYNOPSIS
[verse]
*git-bundle-server* _command_ [_options_]

== DESCRIPTION

The *git-bundle-server* command-line interface configures, generates, and hosts
Git bundles for use with Git's bundle URI feature (see man:git-bundle[1],
man:git-fetch[1]).

A bundle server is comprised of four main components:

1. the repositories for which bundles are generated
2. the base & incremental bundles for each repository
3. the per-repository lists of those bundles
4. the web server hosting the bundle and bundle-list content

Repositories are initialized in the bundle server with the *init* command, which
clones a specified repository and creates an initial bundle for it.
Initialization also adds the repository to a list of repositories that are
updated by the *update-all* command on a daily man:cron[8] schedule.

New incremental bundles are created when the repository is updated, either
manually (with an invocation of *update* or *update-all*) or automatically (via
the man:cron[8] job). The maximum number of bundles per repository is 5; rather
than creating a sixth bundle, the next update will collapse all bundles into a
new base bundle.

Bundle generation for a repository can be stopped with the *stop* command; if a
user wishes to delete all on-disk resources for a repository, *delete* will
remove all existing bundles and internal repository clone as well.

The bundles generated by this server make use of the 'creationToken' heuristic
to help Git clients avoid downloading bundles they already have
footnote:[Details about the 'creationToken' heuristic can be found in the Git
bundle URI technical documentation: url:https://git-scm.com/docs/bundle-uri[]].

To serve the generated bundles, the *web-server* command can be used to start or
stop a configured web server. The server will run in the domain of the user that
invoked the command, and will continue running after the user logs out. The
server does not automatically start on system boot (even if it was running
before prior shutdown), so *web-server start* will need to be invoked to restart
the server.

== COMMANDS

*init* _url_ [_route_]::
  Initialize a repository for which bundles should be served. The repository is
  cloned into a bare repo from _url_. A base bundle is created for the
  repository and used to initialize the bundle list. If _route_ is specified,
  the bundle list will be served from that route; otherwise, the route is
  derived from the _url_. Finally, the man:cron[8] global bundle update schedule
  is started.
+
It is recommended that users specify an SSH (rather than HTTP) URL for the _url_
argument to avoid potentially error-causing authentication prompts while
fetching during scheduled bundle updates.

*start* _route_::
  Start computing bundles for the repository identified by _route_. If the
  man:cron[8] scheduler responsible for periodic bundle updates has not been
  configured, this command starts running a global update schedule as well.

*stop* _route_::
  Stop computing bundles for the repository identified by _route_.

*update* _route_::
  For the repository specified by _route_, fetch the latest content from the
  remote and create a new set of bundles and update the bundle list.

*update-all*::
  Update all initialized repositories with *git-bundle-server update*. This
  command is called via the man:cron[8] scheduler.

*delete* _route_::
  Remove a repository configuration and delete its data on disk.

*web-server* *start* [*-f*|*--force*] [_server-options_]::
  Start a background process web server hosting bundle metadata and content. The
  web server daemon runs under the calling user's domain, and will continue
  running after the user logs out.
+
By default, this command does not restart a running web server process or
overwrite an existing web server configuration. To force that behavior, use the
*--force* option.
+
Additionally, users may provide options that configure the execution of
the man:git-bundle-web-server[1] background process.
+
--
  *-f*:::
  *--force*:::
    If the web server daemon has already been configured, stop the running
    process if needed and rewrite the configuration before starting the service.
    Users should specify this option if they intend to change the web server
    configuration (e.g., the port number).
--
+
***
Server options:
+
--
include::server-options.asc[]
--
+
***

*web-server* *stop* [*--remove*]::
  Stop the web server background process associated with the current user, if
  one is running. Unless the *--remove* option is specified, the service
  configuration is left on disk and remains loaded into the system daemon
  controller.

  *--remove*:::
    In addition to stopping a running web server process, fully unload the
    service configuration and remove any associated daemon config files from
    disk.

== EXAMPLE

Initialize and start generating bundles for the remote repository hosted at
url:https://github.com/rust-lang/rust[]:

[source,console]
----
$ git-bundle-server init git@github.com:rust-lang/rust.git rust-lang/rust
----

Generate an incremental bundle with latest updates to rust-lang/rust:

[source,console]
----
$ git-bundle-server update rust-lang/rust
----

Start an HTTPS web server on port 443 with certificate 'server.crt' and private
key 'server.key':

[source,console]
----
$ git-bundle-server web-server start --force --port 443 --cert server.crt --key server.key
----

== SEE ALSO

man:git-bundle-web-server[1], man:git-bundle[1], man:git-fetch[1]
