= git-bundle-web-server(1)
:doctype: manpage
:manmanual: Git Bundle Server Manual
:mansource: Git Bundle Server

== NAME

git-bundle-web-server - run a web server hosting Git bundle content

== SYNOPSIS
[verse]
*git-bundle-web-server* [_server-options_]

== DESCRIPTION

The *git-bundle-web-server* utility runs a web server on the local machine
serving Git bundle content in accordance with Git's bundle URI feature (see
man:git-bundle*[1], man:git-fetch[1]). The process operates under the assumption that
its content is generated by the man:git-bundle-server[1] CLI; unexpected behavior
may result from manually creating, replacing, or removing bundle content.

This program should generally not be called directly by users outside of niche
debugging scenarios. Instead, users are recommended to use *git-bundle-server
web-server* for managing the web server process on their systems.

== OPTIONS

include::server-options.asc[]

== SEE ALSO

man:git-bundle-server[1], man:git-bundle[1], man:git-fetch[1]
