= git-bundle-web-server(1)
:doctype: manpage
:manmanual: Git Bundle Server Manual
:mansource: Git Bundle Server

== NAME

git-bundle-web-server - run a web server hosting Git bundle content

== SYNOPSIS
[verse]
*git-bundle-web-server* [_server-options_]

== DESCRIPTION

The *git-bundle-web-server* utility runs a web server on the local machine
serving Git bundle content in accordance with Git's bundle URI feature (see
man:git-bundle*[1], man:git-fetch[1]). The process operates under the assumption that
its content is generated by the man:git-bundle-server[1] CLI; unexpected behavior
may result from manually creating, replacing, or removing bundle content.

This program should generally not be called directly by users outside of niche
debugging scenarios. Instead, users are recommended to use *git-bundle-server
web-server* for managing the web server process on their systems.

== OPTIONS

include::server-options.asc[]

== CONFIGURING AUTH

The *--auth-config* option configures authentication middleware for the server,
either using a built-in mode or with a custom plugin. The auth config specified
by that option is a JSON file that identifies the type of access control
requested and information needed to configure it.

=== Schema

The auth config JSON contains the following fields:

*mode* (string)::
  The auth mode to use. Not case-sensitive.

*parameters* (object)::
  A structure containing mode-specific key-value configuration fields, if
  applicable. May be optional, depending on *mode*.

== SEE ALSO

man:git-bundle-server[1], man:git-bundle[1], man:git-fetch[1]
